### PR TITLE
Linear migrations

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
Simple addition - support for linear structure of migrations ( #10 ). Requires the whole store to be linear (migrations must be timestamped to enable correct ordering; relaying on a migrations graph is, in my opinion, not required for this feature) and thus is enabled with global config option (`DBM_LINEAR_MIGRATIONS`).

Modifies how `newCommand` works - if the feature is enabled, it timestamps the migration and selects last migration as a sole dependency. Otherwise works as before.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the patches!  I really appreciate the inclusion of documentation changes and tests!

I'm curious about whether you have considered what will happen when multiple developers, developing on a shared repository containing a migration store, decide to use this feature and then merge their work.  I see it going something like this:

* Developers A and B clone the repo, whose latest migration is M0
* Developers A and B both create migrations M1 and M2 using linear mode, so both M1 and M2 depend on M0
* Developers A and B merge their changes
* Now the upstream repository has broken linearity, since M1 and M2 both depend on M0, thus creating the graph you were trying to avoid.  Manual work is required to restore linearity.

The crux of the issue is that when the timestamp is used to select the latest migration, it is still placed in the dependencies field, thus fixing it for all time (until someone comes along and changes it).  So the ordering of migrations is locally linearized, but merges like the one I described will always break it.

I'm also concerned that it's too easy for users to *fail* to respect linear mode merely by forgetting to set the environment variable.  If this really is a property of the store -- and I think it is -- then that could be avoided by creating a config in the store that `dbmigrations` looks at to figure out what the store's settings are.  (Aside from linear mode, the only other setting that would belong there would be the database type.)

**Comment by jakubfijalkowski** [comment]
Ah, yes, you're totally right. I'm too used to tools that support only linear order (and, mostly, use serial ids to determine it) and I've missed this problem completely.

I've got another idea (basically - do not linearize ordering, but select migrations with 0 in-degree in dep. graph as dependencies) that hopefully will work the way I meant it. However, this time I will try to do much more testing. ;)

For the configuration - I think that using env. variables to configure the app is not the best idea. Mandatory config file with a store path, a database type, a `linear mode` flag and optional default connection string (overridable by env. variable) checked-in repository would be, in my opinion, a better option as this would ensure that every developer respects the settings (or at least makes it harder to not respect them). Having separate configuration for the store and the app would just make it harder to manage.

**Comment by jtdaugherty** [comment]
On configuration, I agree that in general environment variables aren't the greatest way to configure things.  That's why (later on) support for configuration files was added.  However, I think the concern I raised still applies: there needs to be a distinction between *developer-local* configuration and *project-global* configuration.  For example,

* A project that uses PostgreSQL has a *project-global* `DBM_DATABASE_TYPE` setting of `postgresql`.  Unless your project is all about database inter-op, every developer on the project should use this setting.
* That same project may have many developers each using different (possibly local or remote) databases and so they have *developer-local* configuration to set the database connection strings.
* But if the project uses linearized migration mode, it should use it *everywhere* and developers of the project should find it easy to respect this, which means that a configuration file in the store itself should dictate this behavior.  This lets us guarantee that this behavior is consistent even though particular choice of database name may vary.

Does that make sense?

So even if we assume that environment variables aren't a good approach to doing configuration, there is still this issue of where to store which bits of configuration.  The `DBM_DATABASE_TYPE` setting that already exists would be a good candidate for going in this configuration, but if you were to add it in your patch, I think that would be the right home for a linear mode setting, since that is about the *store*.

**Comment by jtdaugherty** [comment]
(Another thought here is that going all-out and putting all configuration in a file means it is too easy to check it into revision control by mistake, thus creating needless and possibly bug-inducing churn in the revision control history.  This is one use case in which environment variables are nice.)

**Comment by jakubfijalkowski** [comment]
Maybe I wasn't clear enough - I don't consider environment variables bad idea. I just think that having completely separate configuration sources (env. + file) is difficult to manage properly. For me, config file should be mandatory (or at least should be a recommended approach) but environment variables should be able to override it. This way, it will be possible to have *project-global* settings (like database type and path to migration files) in a shared file that must (at least partially) be respected by every developer and *developer-local* config in environment variables (not checked into the VCS). For example:

   * `dbmigrations.cfg`

     ```
     DBM_MIGRATION_STORE = migrations
     DBM_DATABASE_TYPE = postgresql
     DBM_DATABASE = "host=localhost dbname=proj_name" # A reasonable default
     DBM_LINEAR_MIGRATIONS = on
     ```
   * Environment:

     ```
     DBM_DATABASE = "..."
     # Or even DBM_DATABASE_TYPE = sqlite3
     ```

**Comment by jtdaugherty** [comment]
Okay.  The approach you described is very close to the current implementation, which supports both and environment variables take precedence.  And I would recommend the approach you described; the only reason it isn't mandatory right now is to avoid breaking setups that existed before the config file support was added.

**Comment by jakubfijalkowski** [comment]
OK, I've finally been able to work on the project. I implemented both the change in `linear mode` and the configuration loading-thing. Unfortunately I haven't had enough time for extensive tests (although I've tested it a little and everything seems fine). I'll be out for about a week and then, if needed, I'll be able to work on this again.

**Comment by jakubfijalkowski** [comment]
OK, it took a little longer, but I've finally managed to work on it again. Both features function the way I expect.

`Linear migrations` may not be linear in the end, but they act as linear, so this name seems reasonable.

Configuration loading works now the way I described it in one of my posts. It tries to load config file, falling back to a default one (`moo.cfg`) if not specified, then overrides its settings with environment variables.

I've also updated `MOO.txt` so that it describes how the configuration loading works.

**Comment by andrewthad** [comment]
Is this going to be merged in?

**Comment by jtdaugherty** [comment]
@jakubfijalkowski - if you can fix the merge conflicts, I'll merge it.

**Comment by andrewthad** [comment]
Done. https://github.com/jtdaugherty/dbmigrations/pull/22

**Pull request merged**
