### PR TITLE
Add option for timestamps on filenames

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR adds a setting in the config file that prepends a timestamp to a migration's filename. This allows the files to be more easily sorted in chronological order for linear migrations.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks!

* What is being used from `MissingH`?
* I've commented in a couple of spots that need to be updated a bit further.

**Comment by parsonsmatt** [comment]
I'm using `Data.List.Utils.replace` from MissingH. I'd be glad to bring that in if you'd prefer to avoid adding the dependency. If so, let me know where you'd like it and I'll put it in.

**Comment by jtdaugherty** [comment]
Thanks for making those style adjustments! As for `replace`, wherever is convenient (an existing module or, say, `Moo.Utils`). It's unfortunate that it isn't in the Prelude but I'd like to avoid adding a dependency unless it's really worth it. :)

**Comment by parsonsmatt** [comment]
I've brought in the code and removed the dependency.

One question: [this test case](https://github.com/layer-3-communications/dbmigrations/blob/72c5c1b78be26b19a484df92d3b44e3c74af658d/test/LinearMigrationsTest.hs#L29-L35) would always fail due to the way the code is written. I wasn't sure whether the test or library would need to be modified so I commented out the test. How would you like that to be?

**Comment by jtdaugherty** [comment]
That test can be removed. The test suite is old and I'm sure I haven't run it enough over the years as the library has evolved. :/

**Comment by jtdaugherty** [comment]
(Feel free to remove it, or I am happy to merge and remove it myself; let me know.)

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by jtdaugherty** [comment]
FYI, so that you know it's coming next time you pull: I removed the Stack configuration from this set of changes once I merged. I don't use Stack so that file will bit-rot and I would prefer to leave it out until it becomes a regular part of how I work with this project.

**Comment by parsonsmatt** [comment]
I'm happy to contribute! I'll keep that in mind re Stack :)

**Comment by jtdaugherty** [comment]
FYI: I just released 1.0 which includes these changes.

http://hackage.haskell.org/package/dbmigrations-1.0

**Pull request merged**
