### PR TITLE
Add support for MySQL databases

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thank you!  Can you also update `MOO.TXT` to mention support for MySQL in the various places where both PostgreSQL and Sqlite are mentioned?

**Comment by ocharles** [comment]
Yep, on it!

**Comment by ocharles** [comment]
Done, also fixed up a few other bits of stale documentation.

**Comment by jtdaugherty** [comment]
Thanks for making those changes!  On the Nix change, I'm concerned that it will just bit rot once it goes in since I don't use Nix.  I'll be compelled to put in a "this isn't maintained" disclaimer for it, so as a result I think it's best if that part is removed.

**Comment by ocharles** [comment]
I only needed that in order to use this until it reaches Hackage. Feel free
to merge up to that commit and discarding that work :)

**Comment by jtdaugherty** [comment]
Okay. Thanks!

**Comment by jtdaugherty** [comment]
By the way: would you be willing to also integrate MySQL into the tests? It should just be a matter of adding a backend to the `backends` list in `tests/TestDriver.hs`.

**Comment by ocharles** [comment]
Thanks for the merge! I might be able to find time to do that tomorrow.

**Pull request merged**
